name: push-check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          check-latest: true
      - name: build
        working-directory: ./src
        run: |
          go version && go build ./cmd/tetris_console_game
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -mode=binary tetris_console_game
