name: tetris
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          check-latest: true
      - name: test
        working-directory: ./src
        run: |
          go test -race -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage reports to Codecov
        working-directory: ./src
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          slug: superfrink/tetris
