name: tetris
on: [push, pull_request]
jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        dir: [. , engine , streamer]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          check-latest: true
      - name: test
        working-directory: .
        run: |
          cd ${{ matrix.dir }}
          echo "${NATS_TEST_CREDS}" > NGS-Default-CLI.creds
          pwd
          ls -l
          go test -race -coverprofile=coverage.out -covermode=atomic ./...
        env:
          NATS_TEST_CREDS: ${{secrets.NATS_TEST_CREDS}}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ matrix.dir }}/coverage.out
          slug: superfrink/tetris
